backend:
  name: git-gateway
  repo: open-voice-network/website
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "events" # Used in the UI, ie.: "New Post"
    folder: "site/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "List Item Title", name: "listItemTitle", widget: "string"}
      - {label: "List Item Image", name: "listItemImage", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "List Item Image Call to Action Text", name: "callToAction", widget: "string"}
      - {label: "Event Date", name: "eventDate", widget: "datetime"}
      - {label: "Presenters Section Header", name: "presentersHeaderText", widget: "string", required: false}
      - {label: "Bio Section Header", name: "bioHeaderText", widget: "string", required: false}
      - {label: "Sponsors Section Header", name: "sponsorsHeaderText", widget: "string", required: false}
      - {label: "Event Page Header Image", name: "pageHeaderBckImge", widget: "image", required: false}
      - {label: "Event Title", name: "eventTitle", widget: "string", required: false}
      - {label: "Event Sub Title", name: "eventSubTitle", widget: "string", required: false}
      - {label: "Event Description", name: "eventDescription", widget: "string", required: false}
      - {label: "Event Information Image", name: "eventInfoImage", widget: "image", required: false}
      - {label: "Event Registration URL", name: "eventRegisterationUrl", widget: "string", required: false}
      - {label: "Event Sessions Header Image", name: "eventSessionsHeaderImage", widget: "image", required: false}
      - label: Sessions
        widget: list
        name: eventSessions
        fields:
          - {label: "Time Slot", name: "timeslot", widget: "date"}
          - {label: "Topic", name: "topic", widget: "string"}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Post Type", name: "posttype", widget: "string",required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "paper" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Paper" # Used in the UI, ie.: "New Document"
    folder: "site/content/paper" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Link to PDF", name: "link_to_document", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:      
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: values, widget: list, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Social", name: "social", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/join/_index.md"
        label: "Join Page"
        name: "join"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Hardsell, name: hardsell, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text} ]}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: About Sections
            name: aboutsections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - {label: TextHTML, name: textHTML, widget: text, required: false}
              - {label: Image, name: imageUrl, widget: image, required: false}
          - label: SteeringCommittee
            name: steeringcommittee
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: SubHeading, name: subHeading, widget: string}
              - {label: Text, name: text, widget: text, required: false}
              - {label: TextHTML, name: textHTML, widget: text, required: false}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/ambassadors/_index.md"
        label: "Ambassadors Page"
        name: "ambassadors"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: About
            name: about
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
          - label: Ambassadors
            name: ambassadors
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/resources/_index.md"
        label: "Resources Page"
        name: "resources"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: text}
          - label: Resources
            name: resources
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: ButtonText, name: buttonText, widget: object}
              - {label: ButtonLink, name: buttonLink, widget: object}
          
      - file: "site/content/voice-chats/_index.md"
        label: Voice Chats
        name: voice-chats
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: text}
          - label: Voice Chats
            name: voicechats
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Video URL, name: videourl, widget: string}
      - file: "site/content/communities/_index.md"
        label: "Communities Page"
        name: "communities"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Communities
            name: communities
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/faq/_index.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Answer, name: answer, widget: text}
      - file: "site/content/sponsoring_member/_index.md"
        label: "Sponsoring Member"
        name: "sponsoring_member"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Hardsell, name: hardsell, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text} ]}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "site/content/supporters/_index.md"
        label: "Friends of the Open Voice Network"
        name: "friends-of-the-open-voice-network"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Hardsell, name: hardsell, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text} ]}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "site/content/voice_interoperability_form/_index.md"
        label: "Voice Interoperability Form"
        name: "Voice nteroperability Form"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: AgendaImage, name: agenda_image, widget: image}
          - {label: AgendaImageALt, name: agenda_image_alt, widget: string}
          - {label: Agenda, name: agenda, widget: markdown}
          - {label: Committee, name: committee, widget: markdown}
      - file: "site/content/industry-advisor-council/_index.md"
        label: "Industry Advisor Council Page"
        name: "industry-advisor-council"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: About
            name: about
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
          - label: Advisors
            name: advisor
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/calendar/_index.md"
        label: "Calendar Page"
        name: "calendar"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: CalendarLink, name: calendarLink, widget: string}
      - file: "site/content/join/positions-to-hire.md"
        label: "Positions to Hire Page"
        name: "positions-to-hire"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Positions
            name: positions
            widget: list
            fields:
              - {label: Job Title, name: job_title, widget: string}
              - {label: Date Posted, name: date_posted, widget: string}
              - {label: Job Description, name: job_description, widget: markdown}
      - file: "site/content/initiatives/_index.md"
        label: "Initiatives Page"
        name: "initiatives"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: SubHeading, name: subheading, widget: string, required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/industries/_index.md"
        label: "Industries Page"
        name: "industries"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: SubHeading, name: subheading, widget: string, required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/friends-of-the-open-voice-network/become-a-friend.md"
        label: "Become a Friend Page"
        name: "become-a-friend"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: SubHeading, name: subheading, widget: string, required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/affiliations/_index.md"
        label: "Affiliations"
        name: "affiliations"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: text, required: false}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: logo, name: logo, widget: image}
              - {label: logo_link, name: logo_link, widget: string}
              - {label: text, name: text, widget: markdown}
      - file: "site/content/audio-reviews/_index.md"
        label: "Audio Reviews Page"
        name: "audio-reviews"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Recorder Snippet, name: recorder, widget: text}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/events/_index.md"
        label: "Events Page"
        name: "events"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string, required: false}
          - {label: Intro, name: intro, widget: string, required: false}
